service: serverless-nestjs-crud

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'eu-central-1'}
  environment:
    DB_TYPE: ${self:custom.dbType.${self:provider.stage}, 'mysql'}
    DB_DATABASE: ${self:custom.dbDatabase.${self:provider.stage}, ':memory:'}
    MYSQL_HOST: ${self:custom.mysqlHost.${self:provider.stage}}
    MYSQL_USER: ${self:custom.mysqlUser.${self:provider.stage}}
    MYSQL_PASSWORD: ${self:custom.mysqlPassword.${self:provider.stage}}
    MYSQL_DATABASE: ${self:custom.mysqlDatabase.${self:provider.stage}}
    MYSQL_PORT: ${self:custom.mysqlPort.${self:provider.stage}}

custom:
  serverless-offline:
    useInProcess: true
  stages:
    - local
    - dev
  dbType:
    local: sqlite
    dev: mysql
  dbDatabase:
    local: '.local.sqlite'
    dev: app
  mysqlHost:
    local: ''
    dev: localhost
  mysqlUser:
    local: root
    dev: root
  mysqlPassword:
    local: ''
    dev: ''
  mysqlDatabase:
    local: app
    dev: app
  mysqlPort:
    local: '3306'
    dev: '3306'

package:
  individually: true

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /
          cors: true
      - http:
          method: any
          path: /{proxy+}
          cors: true
